'use strict';
let draft,token,dirty=false,tab='trip',epoch=0;
const $=s=>document.querySelector(s),clone=x=>JSON.parse(JSON.stringify(x));
const detailKeys=new WeakMap();let detailSerial=0,openNext=null;
function detailKey(row){if(!detailKeys.has(row))detailKeys.set(row,'detail-'+(++detailSerial));return detailKeys.get(row);}
function el(tag,text,attrs={}){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;for(const [k,v]of Object.entries(attrs))node.setAttribute(k,v);return node;}
function message(text,error=false){$('#message').textContent=text;$('#message').classList.toggle('error',error);}
function changed(){dirty=true;epoch++;$('#save-state').textContent='Unsaved changes';}
async function api(path,payload){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Travel-Token':token},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw Error(result.error||'The editor could not finish that action.');return result;}
function download(name,source,type){const url=URL.createObjectURL(new Blob([source],{type}));const a=el('a',undefined,{href:url,download:name});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
const D=(key,label,type='text',options)=>({key,label,type,options});
function field(parent,obj,spec){const {key,label,type='text',options}=spec;const wrap=el('label',undefined,{class:'field'+(type==='lines'||type==='area'?' wide':'')});wrap.append(el('span',label));let input;
  if(type==='select'){input=el('select');for(const value of options){const [v,t]=Array.isArray(value)?value:[value,value];input.append(el('option',t,{value:v}));}}
  else input=el(type==='area'||type==='lines'?'textarea':'input');
  if(input.tagName==='INPUT')input.type=type==='number'?'number':type==='date'?'date':'text';
  if(type==='number'){input.min=1;input.max=10000;input.step=1;}
  input.value=type==='lines'?(obj[key]||[]).join('\n'):(obj[key]??'');
  input.addEventListener('input',()=>{obj[key]=type==='lines'?input.value.split('\n').map(x=>x.trim()).filter(Boolean):type==='number'?(input.value===''?'':Number(input.value)):input.value;changed();});wrap.append(input);parent.append(wrap);return input;
}
function fields(parent,obj,specs){const grid=el('div',undefined,{class:'grid'});for(const s of specs)field(grid,obj,s);parent.append(grid);return grid;}
function check(parent,label,value,onChange){const wrap=el('label',undefined,{class:'check'}),input=el('input',undefined,{type:'checkbox'});input.checked=value;input.addEventListener('change',()=>{onChange(input.checked);changed();});wrap.append(input,el('span',label));parent.append(wrap);return input;}
function membership(array,value,include){const next=array.filter(x=>x!==value);if(include)next.push(value);return next;}
function heading(parent,title,help){parent.append(el('h2',title));if(help)parent.append(el('p',help,{class:'help'}));}
function unique(prefix,rows){let n=1;while(rows.some(x=>x.id===`${prefix}-${n}`))n++;return `${prefix}-${n}`;}
function repeater(parent,title,rows,make,build,label){parent.append(el('h3',title));rows.forEach((row,index)=>{const box=el('details',undefined,{class:'card','data-detail':detailKey(row)}),summary=el('summary',(label?label(row):'Entry')||`Entry ${index+1}`);box.append(summary);build(box,row,index);const remove=el('button','Remove entry',{class:'remove'});remove.addEventListener('click',()=>{if(confirm('Remove this entry from your working copy?')){rows.splice(index,1);changed();draw();}});box.append(remove);parent.append(box);});const add=el('button','Add '+title.toLowerCase().replace(/s$/,''));add.addEventListener('click',()=>{const row=make();rows.push(row);openNext=detailKey(row);changed();draw();});parent.append(add);}
function tripForm(root){heading(root,'Make room for a good trip','Start with the basics. Dates use arrival and departure, so the nights and rental quotes can be compared accurately.');fields(root,draft.trip,[D('title','Trip name'),D('subtitle','Subtitle'),D('destination','Destination'),D('origin','Starting point for drive times'),D('start','Arrival','date'),D('end','Departure','date'),D('party','Who is going (as much or as little detail as you want)','area')]);}
function packingForm(root){heading(root,'Bring the right things','Trip tags suggest items. Your explicit include/exclude choices take priority. Morning-of items appear prominently and again in their category.');const p=draft.packing;
  fields(root,p,[D('note','Packing note','area')]);const tags=el('div',undefined,{class:'chips'});root.append(tags);for(const tag of ['beach','camping','road-trip'])check(tags,tag,p.tags.includes(tag),yes=>{p.tags=membership(p.tags,tag,yes);draw();});
  for(const category of draft.catalog.categories){const box=el('details',undefined,{class:'card','data-detail':detailKey(category)});box.append(el('summary',category.label));fields(box,category,[D('label','Category'),D('note','Category note'),D('column','Print column','select',[['1','Left'],['2','Right']])]);box.querySelector('select').addEventListener('input',()=>category.column=Number(category.column));
    for(const item of draft.catalog.items.filter(x=>x.category===category.id)){const card=el('div',undefined,{class:'card'});const auto=item.tags.includes('universal')||item.tags.some(t=>p.tags.includes(t));const mode={choice:p.excluded.includes(item.id)?'excluded':p.selected.includes(item.id)?'selected':'suggested'};
      fields(card,item,[D('label','Item'),D('quantity','Quantity'),D('assignee','Packed by'),D('note','Note')]);const select=field(card,mode,D('choice','Include in this trip','select',[['suggested','Use tag suggestion: '+(auto?'include':'leave out')],['selected','Always include'],['excluded','Leave out']]));select.addEventListener('input',()=>{p.selected=membership(p.selected,item.id,mode.choice==='selected');p.excluded=membership(p.excluded,item.id,mode.choice==='excluded');});
      check(card,'Check again on departure morning',p.morning.includes(item.id),yes=>p.morning=membership(p.morning,item.id,yes));const tagbox=el('div',undefined,{class:'chips'});card.append(tagbox);for(const tag of ['universal','beach','camping','road-trip'])check(tagbox,tag,item.tags.includes(tag),yes=>{item.tags=membership(item.tags,tag,yes);draw();});
      const remove=el('button','Remove catalog item',{class:'remove'});remove.addEventListener('click',()=>{if(confirm('Remove this item from the catalog?')){draft.catalog.items=draft.catalog.items.filter(x=>x!==item);for(const k of ['selected','excluded','morning'])p[k]=p[k].filter(x=>x!==item.id);changed();draw();}});card.append(remove);box.append(card);
    }
    const add=el('button','Add item here');add.addEventListener('click',()=>{const id=unique('item',draft.catalog.items);draft.catalog.items.push({id,category:category.id,label:'New item',tags:[]});p.selected.push(id);changed();draw();});box.append(add);root.append(box);
  }
  const addCategory=el('button','Add category');addCategory.addEventListener('click',()=>{draft.catalog.categories.push({id:unique('category',draft.catalog.categories),label:'New category',column:1});changed();draw();});root.append(addCategory);
}
function planForm(root){heading(root,'Keep the thinking with the plan','Capture decisions, alternatives, preferences and useful source notes, then carry the lessons into the next trip.');const p=draft.plan;fields(root,p,[D('summary','At a glance','area')]);
  const groups=[['Status',p.status,()=>({label:'New area',value:''}),[D('label','Area'),D('value','Current position'),D('note','Note','area')],x=>x.label],['Days',p.days,()=>({date:draft.trip.start,theme:'New day'}),[D('date','Date','date'),D('theme','Theme'),D('morning','Morning','area'),D('afternoon','Afternoon','area'),D('evening','Evening','area'),D('backup','Backup plan','area')],x=>x.date+' · '+x.theme],['Decisions',p.decisions,()=>({question:'New decision',urgency:'before-trip'}),[D('question','Decision'),D('urgency','Priority','select',['soon','before-trip','optional']),D('owner','Owner'),D('due','Due','date'),D('status','Status'),D('options','Options, one per line','lines'),D('note','Note','area')],x=>x.question],['Activities',p.activities,()=>({name:'New activity'}),[D('name','Activity'),D('description','Description','area'),D('constraints','Constraints','area'),D('source','Source URL')],x=>x.name],['Preferences',p.preferences,()=>({question:'New question',answer:''}),[D('question','Question'),D('answer','Answer','area'),D('owner','Whose preference')],x=>x.question],['Sources',p.sources,()=>({label:'New source'}),[D('label','Source'),D('url','URL'),D('checked','Date checked','date'),D('note','Note','area')],x=>x.label]];
  for(const [title,rows,make,specs,label]of groups)repeater(root,title,rows,make,(box,row)=>fields(box,row,specs),label);
  fields(root,p,[D('notes','Additional notes, one per line','lines')]);if(!p.review)p.review={};heading(root,'After the trip');fields(root,p.review,[D('worked','What worked, one per line','lines'),D('change','What to change, one per line','lines'),D('carryForward','Carry forward, one per line','lines')]);
}
function rentalsForm(root){heading(root,'Pick a place that fits','Keep estimates, exact totals and unknown prices distinct. The full comparison keeps all 22 columns; the gallery brings the photos and practical tradeoffs together.');const r=draft.rentals;fields(root,r,[D('summary','Comparison summary','area'),D('criteria','What matters, one per line','lines')]);const splits={counts:r.splitCounts.join(', ')};const input=field(root,splits,D('counts','Household split scenarios, separated by commas'));input.addEventListener('input',()=>{r.splitCounts=splits.counts.trim()?splits.counts.split(',').map(x=>Number(x.trim())):[];});
  if(!r.hero)r.hero={src:'',alt:''};fields(root,r.hero,[D('src','Header image path (relative to your configuration folder)'),D('alt','Header image description'),D('credit','Header image credit')]);
  repeater(root,'Properties',r.houses,()=>({id:unique('property',r.houses),name:'New property',tier:'alternative',rank:r.houses.length+1,quote:{kind:'unknown',currency:'USD'},photos:[]}), (box,h)=>{
    fields(box,h,[D('name','Property name'),D('tier','Group','select',['shortlist','alternative','rejected']),D('rank','Sort rank','number'),D('rationale','Why it is in this group','area'),...['platform','url','town','drive','sleeps','bedrooms','bathrooms','squareFeet','acreage','waterfront','pool','beds','childPracticalities','rating','cancellation'].map(k=>D(k,({url:'Listing URL',town:'Town / area',drive:'Drive time',squareFeet:'Square feet',childPracticalities:'Practical details for children',beds:'Bed layout'})[k]||k[0].toUpperCase()+k.slice(1))),...['theater','hotTub','gameRoom','sauna'].map(k=>D(k,({theater:'Movie theater',hotTub:'Hot tub',gameRoom:'Game room',sauna:'Sauna'})[k],'select',['unknown','yes','no'])),D('availability','Availability for this trip','select',['unknown','available','unavailable']),D('amenities','Other amenities, one per line','lines'),D('notes','Property notes','area')]);
    box.append(el('h3','The quote'));fields(box,h.quote,[D('kind','Quote type','select',['unknown','range','exact']),D('currency','Currency','select',['USD','EUR','GBP','CAD','AUD','JPY','KWD']),D('amount','Exact stay total (exact quotes only)'),D('min','Low total (range quotes only)'),D('max','High total (range quotes only)'),D('scope','Fees and taxes included / excluded','area'),D('stayStart','Quoted arrival','date'),D('stayEnd','Quoted departure','date'),D('checked','Quote checked','date'),D('note','Quote caveats','area')]);
    box.append(el('p','Local PNG, JPEG and WebP paths are relative to the folder chosen at startup. Remote HTTP(S) photos become links, so the document remains offline. Use images you have permission to share.',{class:'help'}));
    repeater(box,'Photos',h.photos,()=>({src:'',alt:''}),(sub,p)=>fields(sub,p,[D('src','Photo path or URL'),D('alt','Photo description'),D('credit','Credit')]),p=>p.alt||'New photo');
  },h=>h.name);
}
function draw(){const root=$('#fields');const opened=new Set([...root.querySelectorAll('details[open]')].map(x=>x.dataset.detail));if(openNext){opened.add(openNext);openNext=null;}root.replaceChildren();({trip:tripForm,packing:packingForm,plan:planForm,rentals:rentalsForm})[tab](root);for(const box of root.querySelectorAll('details'))box.open=opened.has(box.dataset.detail);for(const button of document.querySelectorAll('[data-tab]')){if(button.dataset.tab===tab)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');}}
for(const button of document.querySelectorAll('[data-tab]'))button.addEventListener('click',()=>{tab=button.dataset.tab;draw();});
$('#save').addEventListener('click',async()=>{const serial=epoch,copy=clone(draft);try{const result=await api('/validate',{source:JSON.stringify(copy)});download('my-trip.json',JSON.stringify(result.document,null,2)+'\n','application/json');if(epoch===serial){dirty=false;$('#save-state').textContent='Downloaded a saved copy';}message('Saved to your browser’s downloads folder. Keep this JSON file to edit the trip later.');}catch(error){message(error.message,true);}});
$('#import').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;if(dirty&&!confirm('Open another trip? Save your current trip first if you want to keep these changes.')){event.target.value='';return;}const serial=epoch;try{if(file.size>2000000)throw Error('Choose a JSON document smaller than 2 MB.');const result=await api('/validate',{source:await file.text()});if(epoch!==serial)throw Error('Your draft changed while the file was opening. Please open it again when ready.');draft=result.document;dirty=false;epoch++;draw();$('#save-state').textContent='Saved trip loaded';$('#frame').srcdoc='';$('#frame').hidden=true;message('Trip opened. Its images must be in the configuration folder chosen at startup.');}catch(error){message(error.message+' Your current draft is unchanged.',true);}finally{event.target.value='';}});
$('#blank').addEventListener('click',()=>{if(dirty&&!confirm('Start a new trip? Save the current trip first if you want to keep it.'))return;draft.trip={title:'My trip',start:'',end:''};draft.packing={tags:[],selected:[],excluded:[],morning:[],note:''};draft.plan={summary:'',status:[],days:[],decisions:[],activities:[],preferences:[],sources:[],notes:[]};draft.rentals={summary:'',criteria:[],splitCounts:[2],houses:[]};changed();tab='trip';draw();$('#frame').srcdoc='';$('#frame').hidden=true;message('A fresh trip is ready. The reusable packing catalog is kept. Choose arrival and departure before saving.');});
async function makeOutput(save){const serial=epoch,kind=$('#kind').value,button=save?$('#download'):$('#preview');button.disabled=true;try{const result=await api('/render',{kind,document:clone(draft)});if(epoch!==serial)throw Error('Your draft changed while the document was being made. Update it again when ready.');$('#frame').srcdoc=result.html;$('#frame').hidden=false;if(save)download('my-trip-'+kind+'.html',result.html,'text/html');message(save?'Document downloaded. Open it in your browser to print or share.':'Preview updated.');}catch(error){message(error.message,true);}finally{button.disabled=false;}}
$('#preview').addEventListener('click',()=>makeOutput(false));$('#download').addEventListener('click',()=>makeOutput(true));
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
fetch('/bootstrap').then(r=>{if(!r.ok)throw Error('Open the editor using the address printed in your terminal.');return r.json();}).then(result=>{draft=result.document;token=result.token;draw();}).catch(error=>message(error.message,true));
